In [1]:
import numpy as np 
from implementations import *
from helpers import *
from helper_functions import *
from optimization import *
%load_ext autoreload
%autoreload 2

In [2]:
%reload_ext autoreload

In [3]:
# load the training dataset
print("loading the training dataset")
DATA_TRAIN_PATH = 'train.csv'
y_tr, tx_tr, ids_tr = load_csv_data(DATA_TRAIN_PATH)
print("training dataset loaded")

loading the training dataset
training dataset loaded


In [4]:
# load the test dataset
print("loading the test dataset")
DATA_TEST_PATH = 'test.csv'
y_te, tx_te, ids_te = load_csv_data(DATA_TEST_PATH)
print("test dataset loaded")

loading the test dataset
test dataset loaded


In [4]:
# printing the shapes of the arrays
print("the shape of the training y is ",y_tr.shape," and the training tx is ", tx_tr.shape)
print("the shape of the test y is ",y_te.shape," and the test tx is ",tx_te.shape)

the shape of the training y is  (250000,)  and the training tx is  (250000, 30)
the shape of the test y is  (568238,)  and the test tx is  (568238, 30)


In [8]:
np.set_printoptions(formatter={'float': lambda x: "{0:10.3f}".format(x)})

def print_col_info(t):
    mean_ = np.nanmean(t, axis=0)
    max_ = np.nanmax(t, axis=0)
    min_ = np.nanmin(t, axis=0)
    median_ = np.nanmedian(t, axis=0)
    std_ = np.nanstd(t, axis=0)
    print(t.shape)

    table = np.vstack([range(t.shape[1]), mean_, max_, min_, median_, std_])

    for line in table.T:
        print(line)

In [5]:
# testing the mean square gd
initial_w = np.zeros(tx_tr.shape[1])
max_iters = 500
gamma = 0.00008

#w, loss = mean_squared_error_gd(y_tr, tx_tr, initial_w, max_iters, gamma)

#print("end of the mean_squared_error_gd with w=",w," and loss=", loss)

In [5]:
# test least square
txOpti = dataClean_without_splitting(tx_tr)
w, loss = least_squares(y_tr, txOpti)
# print("end of the least_squares with w=",w," and loss=", loss)
print("end of the least_squares with loss=", loss)

end of the least_squares with w= [-3.14664000e-01  8.91640668e-02 -2.75720992e-01 -7.01312146e-02
  3.18652180e-03  7.18952546e-02  1.92091255e-02 -7.18571998e-03
  9.49270656e-02 -4.27126248e-02  8.93445861e-03 -6.26613695e-02
  1.03495757e-01  7.09054025e-02  1.55596716e-01 -1.38113243e-03
 -1.72800879e-03  6.05737448e-02 -7.37853585e-04  2.70933535e-03
  2.99658031e-02  1.72500182e-04 -1.18433871e-03 -5.26513161e-02
 -5.56719522e-03  2.24121971e-04 -4.34743233e-04 -5.26989925e-03
  1.05572455e-03 -1.08202820e-03  5.62311347e-02]  and loss= 0.34020330634759505


In [7]:
# test mean squared error sgd

initial_w = np.zeros(tx_tr.shape[1])
max_iters = 100
gamma = 0.00001

#w, loss = mean_squared_error_sgd(y_tr, tx_tr, initial_w, max_iters, gamma)

#print("end of the mean_squared_error_sgd with w=",w," and loss=", loss)

In [6]:
# test ridge regression 

txOpti = dataClean_without_splitting(tx_tr)
print("shape of txOpti ", txOpti.shape)

lambda_ = best_lambda(y_tr, txOpti, -6, 0, 30)
degree = 2
print("best lambda is ",lambda_)

txOpti_poly = build_poly(txOpti, degree)

w, loss = ridge_regression(y_tr, txOpti_poly, lambda_)

label = predict(w, txOpti_poly)
acc = calculate_accuracy(y_tr, label)

print("end of the logistic_regression with w=",w," and loss=", loss)
print("the accuracy on the train set is ", acc)

#y_pred = predict(w, tx_te)
#y_pred[y_pred==0] = -1

#OUTPUT_PATH = 'sample-submission'
#create_csv_submission(ids_te, y_pred, OUTPUT_PATH)

shape of txOpti  (250000, 31)
Current lambda=1e-06, the loss=0.3402033063484495
Current lambda=1.6102620275609392e-06, the loss=0.3402033063498104
Current lambda=2.592943797404667e-06, the loss=0.3402033063533395
Current lambda=4.1753189365604e-06, the loss=0.34020330636248947
Current lambda=6.723357536499335e-06, the loss=0.34020330638621415
Current lambda=1.082636733874054e-05, the loss=0.3402033064477264
Current lambda=1.7433288221999873e-05, the loss=0.3402033066072053
Current lambda=2.8072162039411757e-05, the loss=0.34020330702064727
Current lambda=4.520353656360241e-05, the loss=0.3402033080923542
Current lambda=7.278953843983146e-05, the loss=0.3402033108698735
Current lambda=0.00011721022975334806, the loss=0.34020331806616994
Current lambda=0.00018873918221350977, the loss=0.3402033367022097
Current lambda=0.0003039195382313198, the loss=0.34020338492645996
Current lambda=0.0004893900918477494, the loss=0.3402035095628104
Current lambda=0.0007880462815669912, the loss=0.34020

In [8]:
txOpti, yOpti = dataClean(tx_tr, y_tr)
print("shape of tx_tr ", tx_tr.shape)
print("shape of y_tr ", y_tr.shape)
print("shape of txOpti ", txOpti[0].shape)
print("shape of yOpti ", yOpti[0].shape)

(99913, 19)
(99913,)
(77544, 23)
(77544,)
(50379, 30)
(50379,)
(22164, 30)
(22164,)
shape of tx_tr  (250000, 30)
shape of y_tr  (250000,)
shape of txOpti  (99913, 19)
shape of yOpti  (99913,)


In [ ]:
txs, ys = split_train(tx_tr, y_tr)
for i in range(4):
   print_col_info(txs[i]) 

In [6]:

print(txOpti[0].shape[1])

20


In [23]:
print_col_info(tx_tr)

(250000, 30)
[     0.000    -49.023   1192.026   -999.000    105.012    406.345]
[     1.000     49.240    690.075      0.000     46.524     35.345]
[     2.000     81.182   1349.351      6.329     73.752     40.829]
[     3.000     57.896   2834.999      0.000     38.468     63.656]
[     4.000   -708.421      8.503   -999.000   -999.000    454.480]
[     5.000   -601.237   4974.979   -999.000   -999.000    657.971]
[     6.000   -709.357     16.690   -999.000   -999.000    453.019]
[     7.000      2.373      5.684      0.208      2.492      0.783]
[     8.000     18.917   2834.999      0.000     12.316     22.273]
[     9.000    158.432   1852.462     46.104    120.665    115.706]
[    10.000      1.438     19.773      0.047      1.280      0.845]
[    11.000     -0.128      1.414     -1.414     -0.356      1.194]
[    12.000   -708.985      1.000   -999.000   -999.000    453.596]
[    13.000     38.707    764.408     20.000     31.804     22.412]
[    14.000     -0.011      2.497  

In [25]:
print_col_info(txOpti[0])

(99913, 20)
[     0.000      1.000      1.000      1.000      1.000      0.000]
[     1.000      0.000      3.193     -3.071     -0.059      1.000]
[     2.000     -0.000      2.203     -2.210      0.120      1.000]
[     3.000     -0.000      2.698     -2.620     -0.049      1.000]
[     4.000      0.000      2.191     -1.028     -0.500      1.000]
[     5.000      0.000      2.637     -2.660      0.144      1.000]
[     6.000      0.000      2.191     -1.028     -0.500      1.000]
[     7.000     -0.000      2.599     -1.881     -0.124      1.000]
[     8.000     -0.000      2.258     -2.059     -0.034      1.000]
[     9.000      0.000      6.081     -0.486     -0.337      1.000]
[    10.000     -0.000      2.768     -1.248     -0.262      1.000]
[    11.000      0.000      2.079     -2.046     -0.009      1.000]
[    12.000      0.000      1.875     -1.842     -0.017      1.000]
[    13.000     -0.000      2.516     -1.485     -0.166      1.000]
[    14.000     -0.000      2.001   

/tmp/ipykernel_155/4131380513.py:4: RuntimeWarning: Mean of empty slice
  mean_ = np.nanmean(t, axis=0)
/tmp/ipykernel_155/4131380513.py:5: RuntimeWarning: All-NaN slice encountered
  max_ = np.nanmax(t, axis=0)
/tmp/ipykernel_155/4131380513.py:6: RuntimeWarning: All-NaN slice encountered
  min_ = np.nanmin(t, axis=0)
/usr/local/lib/python3.8/dist-packages/numpy/lib/nanfunctions.py:1096: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanmedian1d, axis, a, overwrite_input)
/usr/local/lib/python3.8/dist-packages/numpy/lib/nanfunctions.py:1879: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,


In [22]:
print_col_info(dataClean_without_splitting(tx_tr))

(250000, 31)
[     0.000      1.000      1.000      1.000      1.000      0.000]
[     1.000     -0.000      3.247     -3.151     -0.043      1.000]
[     2.000     -0.000      2.024     -1.595     -0.042      1.000]
[     3.000     -0.000      2.857     -2.802     -0.062      1.000]
[     4.000      0.000      2.862     -1.218     -0.213      1.000]
[     5.000     -0.000      4.245     -2.663     -0.072      1.000]
[     6.000      0.000      5.977     -1.927     -0.161      1.000]
[     7.000      0.000      4.701     -4.793      0.063      1.000]
[     8.000     -0.000      2.177     -2.270      0.133      1.000]
[     9.000     -0.000      2.625     -1.101     -0.431      1.000]
[    10.000     -0.000      2.824     -1.323     -0.265      1.000]
[    11.000      0.000      2.523     -2.376     -0.082      1.000]
[    12.000      0.000      1.292     -1.077     -0.191      1.000]
[    13.000      0.000      2.536     -2.120     -0.006      1.000]
[    14.000     -0.000      2.958  

In [ ]:
# test logistic regression
#initial_w = np.zeros(txOpti.shape[1])
# initial_w = w
max_iters = 100
gamma = 0.5
ws = []
losses = []
y_pred = []
accArray = []

for i in range(4): 
    initial_w = np.zeros(txOpti[i].shape[1])
    w, loss = logistic_regression(yOpti[i], txOpti[i], initial_w, max_iters, gamma)
    label = predict(w, txOpti[i])
    acc = calculate_accuracy(yOpti[i], label)
    
    ws.append(w)
    losses.append(loss)
    y_pred.append(label)
    accArray.append(acc)

tot_acc = accArray[0] + accArray[1] + accArray[2] + accArray[3]
weights = np.array(list(ws[0])+list(ws[1])+list(ws[2])+list(ws[3]))
loss = np.mean(losses)
    
#teOpti = dataClean(tx_te)
#print("shape of teOpti ", teOpti.shape)

#y_pred = predict(w, teOpti)

#OUTPUT_PATH = 'sample-submission LR 2'
#create_csv_submission(ids_te, y_pred, OUTPUT_PATH)

print("end of the logistic_regression with w=",weights," and loss=", loss)
print("the accurcy on the train set is ", tot_acc)

Preiteration, the loss=1.1116528187695085, the grad=1.2101686786807626
Current iteration=0, the loss=0.6820644832880365, the grad=1.2101686786807626
Current iteration=1, the loss=0.3066142986530485, the grad=1.0084808414933755
Current iteration=2, the loss=-0.029604470798316438, the grad=0.9022029903141847
Current iteration=3, the loss=-0.3430157651992159, the grad=0.8429430779572851
Current iteration=4, the loss=-0.6426399526354077, the grad=0.8069356321121939
Current iteration=5, the loss=-0.9334824700879437, the grad=0.7837460355696775
Current iteration=6, the loss=-1.2184617607782389, the grad=0.768153758030385
Current iteration=7, the loss=-1.4993589564021186, the grad=0.7572877596218334
Current iteration=8, the loss=-1.7773062813172344, the grad=0.749473080028805
Current iteration=9, the loss=-2.053050822127832, the grad=0.743692027158274
Current iteration=10, the loss=-2.3271028598182393, the grad=0.739305993711053
Current iteration=11, the loss=-2.5998222001307125, the grad=0.7

In [15]:
# test logistic regression without splitting 
# txOpti = dataClean_without_splitting(tx_tr)
txOpti = txOpti[0]
y_tr = yOpti[0]
# print("shape of txOpti ", txOpti.shape)
# print("shape of y ", y_tr.shape)
initial_w = np.zeros(txOpti.shape[1])
# initial_w = w
max_iters = 100
gamma = 0.5

w, loss = logistic_regression(y_tr, txOpti, initial_w, max_iters, gamma)

label = predict_logistic(w, txOpti)
acc = calculate_accuracy(y_tr, label)

print("end of the logistic_regression with w=",w," and loss=", loss)
print("the accuracy on the train set is ", acc)

Preiteration, the loss=1.1116528187695085, the grad=203.77505807296845


/home/ml-project-1-ahl/helper_functions.py:62: RuntimeWarning: divide by zero encountered in log
  return -np.sum(y * np.log(sigmoid(v)) + (1 - y) * np.log(1-sigmoid(v)))/N


Current iteration=0, the loss=nan, the grad=203.77505807296845
Current iteration=1, the loss=nan, the grad=99.47051114151297
Current iteration=2, the loss=nan, the grad=99.47051114151297
Current iteration=3, the loss=nan, the grad=99.47051114151297
Current iteration=4, the loss=nan, the grad=99.47051114151297
Current iteration=5, the loss=nan, the grad=99.47051114151297
Current iteration=6, the loss=nan, the grad=99.47051114151297
Current iteration=7, the loss=nan, the grad=99.47051114151297
Current iteration=8, the loss=nan, the grad=99.47051114151297
Current iteration=9, the loss=nan, the grad=99.47051114151297
Current iteration=10, the loss=nan, the grad=99.47051114151297
Current iteration=11, the loss=nan, the grad=99.47051114151297
Current iteration=12, the loss=nan, the grad=99.47051114151297
Current iteration=13, the loss=nan, the grad=99.47051114151297
Current iteration=14, the loss=nan, the grad=99.47051114151297
Current iteration=15, the loss=nan, the grad=99.47051114151297
C

In [ ]:
# test logistic regression without splitting 
# txOpti = dataClean_without_splitting(tx_tr)
txOpti = txOpti[0]
y_tr = yOpti[0]
# print("shape of txOpti ", txOpti.shape)
# print("shape of y ", y_tr.shape)
initial_w = np.zeros(txOpti.shape[1])
# initial_w = w
max_iters = 100
gamma = 0.5

w, loss = logistic_regression(y_tr, txOpti, initial_w, max_iters, gamma)

label = predict_logistic(w, txOpti)
acc = calculate_accuracy(y_tr, label)

print("end of the logistic_regression with w=",w," and loss=", loss)
print("the accuracy on the train set is ", acc)

Preiteration, the loss=1.1116528187695085, the grad=203.77505807296845


/home/ml-project-1-ahl/helper_functions.py:62: RuntimeWarning: divide by zero encountered in log
  return -np.sum(y * np.log(sigmoid(v)) + (1 - y) * np.log(1-sigmoid(v)))/N


Current iteration=0, the loss=nan, the grad=203.77505807296845
Current iteration=1, the loss=nan, the grad=99.47051114151297
Current iteration=2, the loss=nan, the grad=99.47051114151297
Current iteration=3, the loss=nan, the grad=99.47051114151297
Current iteration=4, the loss=nan, the grad=99.47051114151297
Current iteration=5, the loss=nan, the grad=99.47051114151297
Current iteration=6, the loss=nan, the grad=99.47051114151297
Current iteration=7, the loss=nan, the grad=99.47051114151297
Current iteration=8, the loss=nan, the grad=99.47051114151297
Current iteration=9, the loss=nan, the grad=99.47051114151297
Current iteration=10, the loss=nan, the grad=99.47051114151297
Current iteration=11, the loss=nan, the grad=99.47051114151297
Current iteration=12, the loss=nan, the grad=99.47051114151297
Current iteration=13, the loss=nan, the grad=99.47051114151297
Current iteration=14, the loss=nan, the grad=99.47051114151297
Current iteration=15, the loss=nan, the grad=99.47051114151297
C

In [12]:
OUTPUT_PATH = 'logreg_nosplit_072'
create_csv_submission(ids_te, y_pred, OUTPUT_PATH)

In [23]:
#clean column , remove column that has only -999 elements. 
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

median = np.median(tx_tr, axis=0) 
mean = np.mean(tx_tr, axis=0) 

print(median)
print(mean)

indx = np.where(median == -999)
print(indx)

counts = []
count = 0

for i in indx[0]: 
    count = np.count_nonzero( tx_tr[:,i] == -999)
    print("index :", i)
    print(count)
    counts.append(count)

print("counts of each column ", counts)

[105.012 46.524 73.752 38.468 -999.000 -999.000 -999.000 2.492 12.316
 120.665 1.280 -0.356 -999.000 31.804 -0.023 -0.033 40.516 -0.045 0.086
 34.802 -0.024 179.739 1.000 38.960 -1.872 -2.093 -999.000 -999.000
 -999.000 40.513]
[-49.023 49.240 81.182 57.896 -708.421 -601.237 -709.357 2.373 18.917
 158.432 1.438 -0.128 -708.985 38.707 -0.011 -0.008 46.660 -0.020 0.044
 41.717 -0.010 209.797 0.979 -348.330 -399.254 -399.260 -692.381 -709.122
 -709.119 73.065]
(array([ 4,  5,  6, 12, 26, 27, 28]),)
index : 4
177457
index : 5
177457
index : 6
177457
index : 12
177457
index : 26
177457
index : 27
177457
index : 28
177457
counts of each column  [177457, 177457, 177457, 177457, 177457, 177457, 177457]


In [27]:
median = np.median(tx_tr, axis=0) 
indx = np.where(median == -999)
tx1 = np.delete(tx_tr, indx[0], 1)
print(indx[0].shape)
print(tx_tr.shape)
print(tx1.shape)

(7,)
(250000, 30)
(250000, 23)


In [13]:
# test regularized logistic regression
# txOpti = dataClean_without_splitting(tx_tr)
print("shape of txOpti ", txOpti.shape)
print("shape of y ", y_tr.shape)
initial_w = np.zeros(txOpti.shape[1])
max_iters = 100
gamma = 0.5
lambda_ = 0.5

w, loss = reg_logistic_regression(y_tr, txOpti, lambda_, initial_w, max_iters, gamma)

label = predict_logistic(w, txOpti)
acc = calculate_accuracy(y_tr, label)

# print("end of the logistic_regression with w=",w," and loss=", loss)
print("end of the logistic_regression with loss=", loss)
print("the accuracy on the train set is ", acc)

teOpti = dataClean_without_splitting(tx_te)
print("shape of teOpti ", teOpti.shape)

y_pred = predict_logistic(w, teOpti)

OUTPUT_PATH = 'sample-submission LR regression r=1.5, gamma,lambda=0.5'
create_csv_submission(ids_te, y_pred, OUTPUT_PATH)

shape of txOpti  (250000, 31)
shape of y  (250000,)
Current iteration=0, the loss=0.6973502970447647, the grad=1.1243646744140259
Current iteration=1, the loss=0.616856534188257, the grad=0.35775207387661284
Current iteration=2, the loss=0.5787623124787262, the grad=0.13476825801025497
Current iteration=3, the loss=0.564397663619976, the grad=0.05411016582063273
Current iteration=4, the loss=0.5585559036642221, the grad=0.021992177977755455
Current iteration=5, the loss=0.55619834459064, the grad=0.008982988395528583
Current iteration=6, the loss=0.5552395145275486, the grad=0.0036806184561833937
Current iteration=7, the loss=0.5548487730060062, the grad=0.0015121462884724345
Current iteration=8, the loss=0.5546891818181314, the grad=0.000623030677537163
Current iteration=9, the loss=0.5546238925676787, the grad=0.00025755098978636376
Current iteration=10, the loss=0.5545971424561065, the grad=0.00010688905965023133
Current iteration=11, the loss=0.5545861670841631, the grad=4.45718974

In [5]:
jet = tx_tr[:, 22]

values = []

for x in jet: 
    if x not in values: 
        values.append(x) 

print(values) 

[2.0, 1.0, 0.0, 3.0]
